### ISSUE TITLE
Where's the next step after "Getting Started"?

### ISSUE THREAD

**Issue by blzaugg** [electricjs/electricjs.com#11]
NOTE: This is input from Byran's Electric introduction experience. He will be intentionally ignorant.

Page: http://electricjs.com/docs/getting-started.html

After setting up Electric and running the Yeoman generator, I'm expecting some sort of "Next Step". Like what do I do with this, now that I have it.

**Comment by zenorocha** [comment]
+1

**Comment by zenorocha** [comment]
Closing since this has been fixed.
