### ISSUE TITLE
`icon-16-js-file` Icon missing

### ISSUE THREAD

**Issue by jonnilundy** [electricjs/electricjs.com#22]
Looks like one of the icons on Marble is missing.

![image](https://cloud.githubusercontent.com/assets/23219848/26266534/95e82ca4-3c9a-11e7-914e-070e47b810f8.png)

[Issue posted on marble repo as well.](https://github.com/wedeploy/marble/issues/20)

**Comment by ygorcosta** [comment]
The design team has removed this icon from their gallery. So, marble is not providing this icon anymore.

**Comment by ygorcosta** [comment]
Fixed https://github.com/electricjs/electricjs.com/commit/4cdd25edd4160fa10bc974e344bfd98219ca90b6
