### ISSUE TITLE
consider asciidoctor

### ISSUE THREAD

**Issue by peterborkuti** [electricjs/electricjs.com#25]
Hi Developers,

Asciidoctor has the nice feature of including file content from line to line. This is an awesome feature. Think of the use case, when you can save the checked source file (for example a full javascript file for a tutorial) and you can include parts of it and explain the parts.

It is easier to maintain than breaking the whole file into smaller parts, not to mention when you have to copy-paste the whole file into the document.

http://asciidoctor.org/docs/user-manual/#by-line-ranges

In my opinion asciidoctor's syntax is far more superior than markdown.

Maybe Electric can be "Pluggable" with different "input drivers", like markdown, asciidoc, soy, etc.
If the input file can be a soy file, we could migrate MetalJs easier.

**Comment by zenorocha** [comment]
Hey @peterborkuti, thank you so much for this suggestion. Unfortunately we don't have bandwidth to work on this right now, but we really appreciate the feedback.
