### ISSUE TITLE
Font line heights are inconsitant

### ISSUE THREAD

**Issue by blzaugg** [electricjs/electricjs.com#6]
![font line heights](https://cloud.githubusercontent.com/assets/1626739/21824529/aec6889a-d734-11e6-8aad-8d5b80770791.PNG)

![font line heights 2](https://cloud.githubusercontent.com/assets/1626739/21827430/62130cd8-d740-11e6-9807-dba5e86a5b61.PNG)

Windows 7 Pro
Chrome, Firefox, IE11

**Comment by zenorocha** [comment]
This should be fixed on the newest version of Marble.
