### ISSUE TITLE
Metal.js is not a "familiar" tool among the "community"

### ISSUE THREAD

**Issue by blzaugg** [electricjs/electricjs.com#9]
NOTE: This is input from Byran's Electric introduction experience. I will be intentionally ignorant.

One of these things is not like the other...

Page: http://electricjs.com/

> How?
> We're not trying to reinvent the wheel here. Our idea is to leverage existing and well established tools, so you can feel more familiar with the workflow, worry less about tooling, and focus on what's important.

We then list Metal.js among, generally, familiar tools, in the frontend dev community.

I'm not 100% sure the "community" Electric targets, Liferay vs general dev. But, in either of those, I wouldn't consider it a "familiar" tool.

Also, as, I've not read through all the docs, to understand Metal.js involvement, I don't know why it's there. I hope to learn as I dig in.

**Comment by zenorocha** [comment]
That's true. In fact, this section is a little bit tricky because we're mixing the theming part of it (Sass and Metal) with the tooling itself (Soy and Markdown).

**Comment by zenorocha** [comment]
Closing this one for now. Please send a pull request if you have a suggestion.
